apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: "rootpassword"
  MYSQL_USER: "attendance_user"
  MYSQL_PASSWORD: "attendance_pass"
  MYSQL_DATABASE: "attendancemsystem"
  JWT_SECRET: "Cny2gL5Ti9zdMAFdpeWR1bFRprQlRyYQg3gaPd79iek="
