apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: management-service
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/student-attendance-system/management-service.git'
    targetRevision: HEAD
    path: k8s   # folder containing frontend + backend manifests
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
