apiVersion: v1
kind: Service
metadata:
  name: node-exporter
  namespace: monitoring
  labels:
    app: node-exporter
spec:
  clusterIP: None   # headless, Prometheus discovers pods directly
  ports:
    - name: metrics
      port: 9100
      targetPort: 9100
  selector:
    app: node-exporter

